# Generated by Django 4.1.7 on 2023-03-10 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=3000, verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End date')),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Status')),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Type')),
            ],
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=200, verbose_name='Summary')),
                ('description', models.TextField(blank=True, max_length=3000, null=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Time created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Time updated')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='Deleted')),
                ('deleted_at', models.DateTimeField(default=None, null=True, verbose_name='Deletion time')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='issues', to='tracker.project')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='issues', to='tracker.status')),
                ('type', models.ManyToManyField(blank=True, related_name='issues', to='tracker.type')),
            ],
        ),
    ]
